name: .NET Build and Test

on:
  push:
    branches:
      - master  # Change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust the version as needed
        
    - name: Restore dependencies
      run: dotnet restore
      with:
        path: MangoV2
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
